[package]
name = "testausclip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
actix-files = "0.6.5"
confy = "0.6.0"
serde = "1.0.196"
serde_derive ="1.0.196"