CREATE TABLE Users (
    id VARCHAR(255) PRIMARY KEY UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100),
    password BYTEA NOT NULL,
    salt BYTEA NOT NULL,
    auth_token VARCHAR(32) NOT NULL UNIQUE,
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)